### ISSUE TITLE
Comportement du bouton « Membres »

### ISSUE THREAD

**Issue by Galixte** [MrGabatt/BasicForPhpBB32#1]
Salut @MrGabatt,

je viens en remettre une couche, car j’y tiens, concernant ceci : http://forums.phpbb-fr.com/modifications-et-recherche-de-styles-phpbb32/sujet210588.html#p1648137.

Pourrais-tu faire en sorte de l’intégrer dans ta CSS « minimifiée », je te prie ? :)

Voici les liens pour les autres styles, car chaque style ne reçoit pas exactement les mêmes modifications nécessaires :
- Black (Arty) pour phpBB 3.2 : http://forums.phpbb-fr.com/modifications-et-recherche-de-styles-phpbb32/sujet210586.html#p1648140 ;
- Digi (Arty) pour phpBB 3.2 : http://forums.phpbb-fr.com/modifications-et-recherche-de-styles-phpbb32/sujet210535-15.html#p1648138 ;
- Elegance (Arty) pour phpBB 3.2 : http://forums.phpbb-fr.com/modifications-et-recherche-de-styles-phpbb32/sujet210067-30.html#p1648141 ;
- Latte (Arty) pour phpBB 3.2 : http://forums.phpbb-fr.com/modifications-et-recherche-de-styles-phpbb32/sujet210587.html#p1648142 ;
- Simplicity (Arty) pour phpBB 3.2 : http://forums.phpbb-fr.com/modifications-et-recherche-de-styles-phpbb32/sujet210540.html#p1648143.

Bien entendu, et comme déjà proposé, je peux te préparer le PR pour chacun de tes styles si tu me confirmes que j’ai juste à intégrer les modifications dans le fichier : https://github.com/MrGabatt/BasicForPhpBB32/blob/master/basic/theme/stylesheet.scss (et leurs équivalents pour chacun des styles et leurs variantes).

D’ailleurs j’ai une question : la compilation proposée par l’extension de Arty sert juste à faire « déminifier » les règles a CSS de :
https://github.com/MrGabatt/BasicForPhpBB32/blob/master/basic/theme/stylesheet.scss (tenant sur une ligne) vers https://github.com/MrGabatt/BasicForPhpBB32/blob/master/basic/theme/stylesheet.css (pour les présenter sur plusieurs lignes), ou est-ce dans le sens inverse : ```stylesheet.scss``` vers ```stylesheet.scss``` ? Ou alors j’y suis pas et cela sert à autre chose ?

**Comment by MrGabatt** [comment]
Salut @Galixte 

Modifications effectuées. Il m'a fallu aller un peu plus loin que ce que tu proposais pour prendre en compte le paramétrage 'rtl' éventuel du forum.

Comme expliqué sur le forum, il ne faut pas, dans les thèmes d'Arty, modifier directement le fichier stylesheet.css, au risque de perdre les modifications à la prochaine compilation.

La compilation lit le fichier stylesheet.**s**css, et va chercher tous les fichiers scss indiqués pour les compiler en un seul. C'est ce processus qui crée le fichier stylesheet.css.

C'est pour cela, apr exemple, qu'il a fallu modifier le fichier '_common.scss' pour appliquer les modifications que tu as proposées, et ensuite lancer la compilation pour appliquer les modifications.

Encore merci pour ta proposition.

**Comment by Galixte** [comment]
Salut @MrGabatt,

non c’est moi qui te remercie ! :)

Du coup maintenant je cerne un peu mieux ce que permet l’outil d’Arty.

Au final phpBB il lit quoi, uniquement le fichiers fichiers *.css ou aussi les fichiers *.scss ?

En passant, si tu le souhaites tu peux « twigifier » tes styles, voir mon message à ce propos : http://www.ezcom-fr.com/viewtopic.php?p=3648#p3648. ;)

Je te ferai un retour d’utilisation dans les prochains jours.

**Comment by MrGabatt** [comment]
Oui, phpBB ne lit que le fichier css, c'est un des avantages de SASS, un seul fichier à lire.

Je regarderai pour Twig.
